version: '3.3'
services:
   app:
     image: "training-app:v1.0
     build:
       context: .
       dockerfile: Dockerfile-training-app
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: training-app
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8000:80"
     restart: always
volumes:
    dbdata:
